version: '3'

services:
  db:
    image: mysql:8.0.30
    restart: always
    env_file:
      .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/db.d
  api:
    build: .
    depends_on:
      - db
    env_file:
      .env
    image: kawaiimelnik/books_test:api
    restart: always
    ports:
      - "8071:8071"
volumes:
  my-db:
